name: CI

on:
  pull_request:
  push:
  release:
    types: [published]

env:
  IMAGE_ID: ${{ github.repository }}

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0

      - name: Docker Buildx setup
        id: buildx
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25 # renovate: tag=v1.6.0

      - name: Registry login
        if: github.event_name != 'pull_request'
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USER_NAME }}" --password-stdin

      - name: Build
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker buildx build \
            --cache-from=$IMAGE_ID:cache \
            --load \
            -t stage_build \
            --target build \
            .
          docker container create --name extract stage_build
          docker container cp extract:/srv/app/ ./dist/
          docker container rm -f extract

          # Push the Docker image to the registry on git pushes that either pushed a tag or one of the following branches: [master, develop]
          if [[
            (
              "${{ github.event_name }}" == "create"
              &&
              ${{ startsWith(github.ref, 'refs/tags/') }} == "true"
            )
            ||
            (
              "${{ github.event_name }}" == "push"
              &&
              ${{ startsWith(github.ref, 'refs/heads/') }} == "true"
              &&
              (
                $VERSION == "latest"
                ||
                $VERSION == "develop"
              )
            )
          ]]
          then
            docker buildx build \
              --cache-from=$IMAGE_ID:cache \
              --cache-to=$IMAGE_ID:cache \
              --push \
              -t $IMAGE_ID:$VERSION \
              .
          else
            docker buildx build \
              --cache-from=$IMAGE_ID:cache \
              -t $IMAGE_ID:$VERSION \
              .
          fi

      - name: Zip
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: montudor/action-zip@0852c26906e00f8a315c704958823928d8018b28 # renovate: tag=v1.0.0
        with:
          args: zip -qq -r ./${{ github.event.repository.name }}.zip ./dist/

      - uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # renovate: tag=v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          name: ${{ github.event.repository.name }}.zip
          path: ./${{ github.event.repository.name }}.zip
          retention-days: 1
  semantic-release:
    if: github.event_name != 'pull_request'
    name: Semantic Release
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@5982a02995853159735cb838992248c4f0f16166 # renovate: tag=v2.7.0
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  release-assets:
    if: startsWith(github.ref, 'refs/tags/')
    name: Release Assets
    runs-on: ubuntu-latest
    needs: semantic-release
    steps:
      - uses: actions/download-artifact@f023be2c48cc18debc3bacd34cb396e0295e2869 # renovate: tag=v2
        with:
          name: ${{ github.event.repository.name }}.zip

      - name: GitHub Release Asset
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5 # renovate: tag=v1
        with:
          files: ${{ github.event.repository.name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
